import React, {useState, useEffect}  from 'react'
import Chart from "chart.js/auto";
import {
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  Box,
  Center,
  Container,
  Text,
  Heading,
  Flex
} from '@chakra-ui/react';
import { Line } from "react-chartjs-2";
import CarbonFootprintService from 'requests/services/CarbonFootprintService';

const options = {
  legend:{
    labels:{
      font:{
        size:30,
      }
    }
  },
  scales: {
      x: {
          beginAtZero: true,
          title:{
              display: true,
              text: "Month",
              font:{
                size: 20,
                weight: "bold",
              }
          },
          ticks: {
              font: {
                  size: 20,
              },
          },
      },
      y:{
        beginAtZero: false,
        title:{
          display: true,
          text: "Carbon Footprint (Watts)",
          font:{
            size: 20,
            weight: "bold",
          }
        },
        ticks: {
          max: 500000,
          font: {
              size: 20,
          }
        }
      },

  }
};



function CarbonChart() {

  const SESSION_ACCOUNT_GUID = "11111111-1111-1111-1111-111111111111";

  const [graphData, setGraphData] = useState(null);


  function getCarbonFootprintData(){
    const current = new Date()
    CarbonFootprintService.getCarbonFootprintData(SESSION_ACCOUNT_GUID, current.getFullYear(), current.getMonth())
      .then((response) =>{
        const carbonFootprintData = response.data.data;
        const graph = {
          labels: [],
          datasets: [
            {
              label: "My Household Carbon Footprint",
              backgroundColor: "rgb(255, 99, 132)",
              borderColor: "rgb(255, 99, 132)",
              data: [],
            },
            {
              label: "National Household Average Carbon Footprint",
              backgroundColor: "rgb(124,252,0)",
              borderColor: "rgb(124,252,0)",
              data: [],
            },
          ],
        }
        
        graph.datasets[0].data = carbonFootprintData.map((data) => {
          return data.householdConsumption
        })
        graph.datasets[1].data = carbonFootprintData.map((data) => {
          return data.nationalHouseholdConsumption
        })
        graph.labels = carbonFootprintData.map((data) => {
          return `${data.yearOfAnalysis}-${data.monthOfAnalysis.toString().padStart(2, '0')}`
        })
        setGraphData(graph);
      })
  }

  useEffect(() => {
    getCarbonFootprintData()
  }, [])

  return (
    <Flex direction="column" justify="center" align="center">
      <Heading pb={5}>Carbon Footprint</Heading>
      <Text pb={10}>
        This is your carbon footprint. Carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.
      </Text>
      {graphData && <Line options={options} data={graphData} />}
    </Flex>
  )
}

export default CarbonChart