import React, {useState, useEffect}  from 'react'
import Chart from "chart.js/auto";
import {
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  Box,
  Center,
  Container,
  Text,
  Heading,
  Flex
} from '@chakra-ui/react';
import { Line } from "react-chartjs-2";
import CarbonFootprintService from 'requests/services/CarbonFootprintService';





const options = {
  legend:{
    labels:{
      font:{
        size:30,
      }
    }
  },
  scales: {
      x: {
          beginAtZero: true,
          title:{
              display: true,
              text: "Month",
              font:{
                size: 30,
                weight: "bold",
              }
          },
          ticks: {
              font: {
                  size: 30,
              },
          },
      },
      y:{
        beginAtZero: true,
        title:{
          display: true,
          text: "Carbon Footprint",
          font:{
            size: 30,
            weight: "bold",
          }
      },
        ticks: {
          font: {
              size: 30,
          }
      }
      },

  }
};



function CarbonChart() {

  const SESSION_ACCOUNT_GUID = "11111111-1111-1111-1111-111111111111";

  const [carbonFootprintData, setCarbonFootprintData] = useState(null)

 const [graphData,setGraphData] = useState({
  labels: ["1","2","3"],
  datasets: [
    {
      label: "My Household Carbon Footprint",
      backgroundColor: "rgb(255, 99, 132)",
      borderColor: "rgb(255, 99, 132)",
      data: [1,2,3],
    },
    {
      label: "National Household Average Carbon Footprint",
      backgroundColor: "rgb(124,252,0)",
      borderColor: "rgb(124,252,0)",
      data: [4,5,6],
    },
  ],
}) 



  

function getCarbonFootprintData(){
    const current = new Date()
    CarbonFootprintService.getCarbonFootprintData(SESSION_ACCOUNT_GUID, current.getFullYear(), current.getMonth())
      .then((response) =>{
        setCarbonFootprintData(response.data.data)
        
      })
  }

  useEffect(() => {
    getCarbonFootprintData()
  }, [])


  useEffect(() =>{
    console.log("inside useeffect ")
    if(carbonFootprintData){
      const newGraphData = graphData
      newGraphData.datasets[0].data = carbonFootprintData.map((data) => {
        return data.householdConsumption
      })
      newGraphData.datasets[1].data = carbonFootprintData.map((data) => {
        return data.nationalHouseholdConsumption
      })
      newGraphData.labels = carbonFootprintData.map((data) => {
        return `${data.yearOfAnalysis}-${data.monthOfAnalysis.toString().padStart(2, '0')}`
      })
      graphData = newGraphData
      console.log(graphData)
    }
  }, [carbonFootprintData])


  




  return (
        <Flex direction="column" justify="center" align="center">
          <Heading pb={5}>Carbon Footprint</Heading>
          <Text pb={10}>This is your carbon footprint. Carbon footprint is the total amount of greenhouse gases 
              (including carbon dioxide and methane) that are generated by our actions.</Text>
          {carbonFootprintData && <Line options={options} data={graphData} />}
          
        </Flex>
    
  )
}

export default CarbonChart